language: go

go:
  - 1.7

matrix:
  - fast_finish: true

install:
  - export GOPATH=$HOME/gopath
  - export PATH=$PATH:$HOME/gopath/bin
  - make deps
  - cd $GOPATH/src/github.com/tendermint/light-client && git checkout -qf 287d501e668d0ec9fd48c8f785ad442ab1d79ff7  
  - cd $GOPATH/src/github.com/tendermint/clearchain

script:
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - make ci
  - make test
  - make lint
